/* create new DB */
CREATE DATABASE if not exists `flights`;

/* Create flights raw table */
DROP TABLE IF EXISTS flights.flights_raw;
CREATE TABLE flights.flights_raw (
    TRANSACTIONID TEXT,
    FLIGHTDATE TEXT,
    AIRLINECODE TEXT,
    AIRLINENAME TEXT,
    TAILNUM TEXT,
    FLIGHTNUM TEXT,
    ORIGINAIRPORTCODE TEXT,
    ORIGAIRPORTNAME TEXT,
    ORIGINCITYNAME TEXT,
    ORIGINSTATE TEXT,
    ORIGINSTATENAME TEXT,
    DESTAIRPORTCODE TEXT,
    DESTAIRPORTNAME TEXT,
    DESTCITYNAME TEXT,
    DESTSTATE TEXT,
    DESTSTATENAME TEXT,
    CRSDEPTIME TEXT,
    DEPTIME TEXT,
    DEPDELAY TEXT,
    TAXIOUT TEXT,
    WHEELSOFF TEXT,
    WHEELSON TEXT,
    TAXIIN TEXT,
    CRSARRTIME TEXT,
    ARRTIME TEXT,
    ARRDELAY TEXT,
    CRSELAPSEDTIME TEXT,
    ACTUALELAPSEDTIME TEXT,
    CANCELLED TEXT,
    DIVERTED TEXT,
    DISTANCE TEXT
);

/* Load the flights raw data into the table */
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 9.4/Uploads/flights.txt' INTO TABLE flights.flights_raw FIELDS TERMINATED BY '|'
IGNORE 1 ROWS (TRANSACTIONID,
               FLIGHTDATE,
               AIRLINECODE,
               AIRLINENAME,
               @TAILNUM,
               FLIGHTNUM,
               ORIGINAIRPORTCODE,
               ORIGAIRPORTNAME,
               ORIGINCITYNAME,
               ORIGINSTATE,
               ORIGINSTATENAME,
               DESTAIRPORTCODE,
               DESTAIRPORTNAME,
               DESTCITYNAME,
               DESTSTATE,
               DESTSTATENAME,
               @CRSDEPTIME,
               @DEPTIME,
               @DEPDELAY,
               @TAXIOUT,
               @WHEELSOFF,
               @WHEELSON,
               @TAXIIN,
               @CRSARRTIME,
               @ARRTIME,
               @ARRDELAY,
               @CRSELAPSEDTIME,
               @ACTUALELAPSEDTIME,
               CANCELLED,
               DIVERTED,
               @DISTANCE)
SET TAILNUM=nullif(@TAILNUM, ''),
    CRSDEPTIME=NULLIF(@CRSDEPTIME, ''),
    DEPTIME = NULLIF(@DEPTIME, ''),
    WHEELSOFF = NULLIF(@WHEELSOFF, ''),
    WHEELSON = NULLIF(@WHEELSON, ''),
    CRSARRTIME = NULLIF(@CRSARRTIME, ''),
    ARRTIME=NULLIF(@ARRTIME, ''),
    DEPDELAY=nullif(@DEPDELAY, ''),
    ARRDELAY=nullif(@ARRDELAY, ''),
    TAXIOUT=nullif(@TAXIOUT, ''),
    TAXIIN=nullif(@TAXIIN, ''),
    CRSELAPSEDTIME=nullif(@CRSELAPSEDTIME, ''),
    ACTUALELAPSEDTIME=nullif(@ACTUALELAPSEDTIME, ''),
    DISTANCE=nullif(@DISTANCE, '');
